// lib/latex.js — renders resume modules into a compilable LaTeX document
// following Jake Gutierrez's widely used resume template ("Jake's Resume").
//
// Every string literal here uses String.raw so a LaTeX command like
// \resumeItem stays literal instead of being read as a JS escape (\r).

import { SECTION_TITLES, TYPE_ORDER } from "./constants";

// ---------------------------------------------------------------- escaping

const ESCAPES = {
  "\\": String.raw`\textbackslash{}`,
  "&": String.raw`\&`,
  "%": String.raw`\%`,
  $: String.raw`\$`,
  "#": String.raw`\#`,
  _: String.raw`\_`,
  "{": String.raw`\{`,
  "}": String.raw`\}`,
  "~": String.raw`\textasciitilde{}`,
  "^": String.raw`\textasciicircum{}`
};

/** Makes arbitrary user text safe to drop into a LaTeX document. */
export function escapeLatex(value) {
  if (value === null || value === undefined) return "";
  return String(value)
    // Curly quotes and long dashes that users paste out of job postings
    // render badly in pdfLaTeX, so fold them to ASCII first.
    .replace(/[‘’]/g, "'")
    .replace(/[“”]/g, '"')
    .replace(/[–—]/g, "--")
    .replace(/…/g, "...")
    .replace(/[\\&%$#_{}~^]/g, ch => ESCAPES[ch]);
}

// ---------------------------------------------------------------- preamble

const PREAMBLE = String.raw`%-------------------------------------------
% Resume in LaTeX -- "Jake's Resume" template
% Author: Jake Gutierrez (https://github.com/jakegut/resume)
% License: MIT
% Generated by Casefile. Edit freely, or regenerate after changing modules.
%-------------------------------------------

\documentclass[letterpaper,11pt]{article}

\usepackage{latexsym}
\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage{marvosym}
\usepackage[usenames,dvipsnames]{color}
\usepackage{verbatim}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage{fancyhdr}
\usepackage[english]{babel}
\usepackage{tabularx}
\input{glyphtounicode}

\pagestyle{fancy}
\fancyhf{}
\fancyfoot{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

% Adjust margins
\addtolength{\oddsidemargin}{-0.5in}
\addtolength{\evensidemargin}{-0.5in}
\addtolength{\textwidth}{1in}
\addtolength{\topmargin}{-.5in}
\addtolength{\textheight}{1.0in}

\urlstyle{same}

\raggedbottom
\raggedright
\setlength{\tabcolsep}{0in}

% Section formatting
\titleformat{\section}{
  \vspace{-4pt}\scshape\raggedright\large
}{}{0em}{}[\color{black}\titlerule \vspace{-5pt}]

% Keep the generated PDF machine readable so applicant tracking systems can
% parse it.
\pdfgentounicode=1

%-------------------------
% Custom commands
\newcommand{\resumeItem}[1]{
  \item\small{
    {#1 \vspace{-2pt}}
  }
}

\newcommand{\resumeSubheading}[4]{
  \vspace{-2pt}\item
    \begin{tabular*}{0.97\textwidth}[t]{l@{\extracolsep{\fill}}r}
      \textbf{#1} & #2 \\
      \textit{\small#3} & \textit{\small #4} \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeSubSubheading}[2]{
    \item
    \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
      \textit{\small#1} & \textit{\small #2} \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeProjectHeading}[2]{
    \item
    \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
      \small#1 & #2 \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeSubItem}[1]{\resumeItem{#1}\vspace{-4pt}}

\renewcommand\labelitemii{$\vcenter{\hbox{\tiny$\bullet$}}$}

\newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=0.15in, label={}]}
\newcommand{\resumeSubHeadingListEnd}{\end{itemize}}
\newcommand{\resumeItemListStart}{\begin{itemize}}
\newcommand{\resumeItemListEnd}{\end{itemize}\vspace{-5pt}}`;

// ----------------------------------------------------------------- helpers

function bulletsOf(module) {
  if (!Array.isArray(module.bullets)) return [];
  return module.bullets.map(b => String(b).trim()).filter(Boolean);
}

/** "May 2023 -- Present", or whichever single side was filled in. */
export function dateRange(module) {
  const start = (module.startDate || "").trim();
  const end = (module.endDate || "").trim();
  if (start && end) return `${start} -- ${end}`;
  return start || end;
}

function href(url, label) {
  const raw = String(url || "").trim();
  const withScheme = /^[a-z]+:/i.test(raw) ? raw : `https://${raw}`;
  return String.raw`\href{${escapeLatex(withScheme)}}{\underline{${escapeLatex(label)}}}`;
}

function renderHeading(profile) {
  const p = profile || {};
  const name = (p.name || "Your Name").trim();
  const pieces = [];
  if (p.phone) pieces.push(escapeLatex(p.phone));
  if (p.location) pieces.push(escapeLatex(p.location));
  if (p.email) {
    pieces.push(String.raw`\href{mailto:${escapeLatex(p.email)}}{\underline{${escapeLatex(p.email)}}}`);
  }
  (p.links || []).forEach(link => {
    if (!link || !link.url) return;
    pieces.push(href(link.url, link.label || link.url));
  });

  const separator = String.raw` $|$ `;
  const contactLine = pieces.length
    ? String.raw`    \small ${pieces.join(separator)}`
    : String.raw`    \small ~`;

  return [
    String.raw`\begin{center}`,
    String.raw`    \textbf{\Huge \scshape ${escapeLatex(name)}} \\ \vspace{1pt}`,
    contactLine,
    String.raw`\end{center}`
  ].join("\n");
}

function renderItemList(module) {
  const lead = (module.content || "").trim();
  const bullets = bulletsOf(module);
  if (!lead && bullets.length === 0) return "";

  const lines = [String.raw`      \resumeItemListStart`];
  if (lead) {
    lead.split(/\n{2,}/).forEach(para => {
      const text = para.replace(/\n/g, " ").trim();
      if (text) lines.push(String.raw`        \resumeItem{${escapeLatex(text)}}`);
    });
  }
  bullets.forEach(b => {
    lines.push(String.raw`        \resumeItem{${escapeLatex(b)}}`);
  });
  lines.push(String.raw`      \resumeItemListEnd`);
  return lines.join("\n");
}

// -------------------------------------------------------- per-type entries

// Jake's template feeds the four subheading slots in a different order for
// education than for experience, which is why these are separate functions.
function renderExperienceEntry(module) {
  const lines = [
    String.raw`    \resumeSubheading`,
    String.raw`      {${escapeLatex(module.title)}}{${escapeLatex(dateRange(module))}}`,
    String.raw`      {${escapeLatex(module.organization)}}{${escapeLatex(module.location)}}`
  ];
  const items = renderItemList(module);
  if (items) lines.push(items);
  return lines.join("\n");
}

function renderEducationEntry(module) {
  // Institution on the bold line, degree on the italic line below it.
  const institution = module.organization || module.title;
  const degree = module.organization ? module.title : "";
  const lines = [
    String.raw`    \resumeSubheading`,
    String.raw`      {${escapeLatex(institution)}}{${escapeLatex(module.location)}}`,
    String.raw`      {${escapeLatex(degree)}}{${escapeLatex(dateRange(module))}}`
  ];
  const items = renderItemList(module);
  if (items) lines.push(items);
  return lines.join("\n");
}

function renderProjectEntry(module) {
  // `organization` doubles as the tech-stack slot for projects, matching the
  // "Name $|$ Tech, Stack" heading in the template.
  const stack = (module.organization || "").trim();
  const heading = stack
    ? String.raw`\textbf{${escapeLatex(module.title)}} $|$ \emph{${escapeLatex(stack)}}`
    : String.raw`\textbf{${escapeLatex(module.title)}}`;
  const lines = [
    String.raw`    \resumeProjectHeading`,
    String.raw`      {${heading}}{${escapeLatex(dateRange(module))}}`
  ];
  const items = renderItemList(module);
  if (items) lines.push(items);
  return lines.join("\n");
}

/** Skills render as "Label: items" lines rather than as bullet points. */
function renderSkillSection(modules) {
  const rows = [];
  modules.forEach(module => {
    const lead = (module.content || "").trim();
    if (lead) rows.push(String.raw`     ${escapeLatex(lead)}`);
    bulletsOf(module).forEach(line => {
      const split = line.indexOf(":");
      if (split > 0) {
        const label = line.slice(0, split).trim();
        const items = line.slice(split + 1).trim();
        rows.push(String.raw`     \textbf{${escapeLatex(label)}}{: ${escapeLatex(items)}}`);
      } else {
        rows.push(String.raw`     ${escapeLatex(line)}`);
      }
    });
  });

  if (rows.length === 0) return "";
  return [
    String.raw` \begin{itemize}[leftmargin=0.15in, label={}]`,
    String.raw`    \small{\item{`,
    // Rows are separated by a LaTeX line break, but the final row must not
    // end with one or pdfLaTeX errors with "There's no line here to end".
    rows.join(String.raw` \\` + "\n"),
    String.raw`    }}`,
    String.raw` \end{itemize}`
  ].join("\n");
}

/** A summary is a plain paragraph, with no itemize wrapper. */
function renderSummarySection(modules) {
  const paras = [];
  modules.forEach(module => {
    const text = [(module.content || "").trim(), ...bulletsOf(module)]
      .filter(Boolean)
      .join(" ");
    if (text) paras.push(escapeLatex(text.replace(/\s+/g, " ").trim()));
  });
  if (paras.length === 0) return "";
  return paras.map(p => String.raw` \small{${p}}`).join(String.raw` \\ ` + "\n");
}

function renderSection(type, modules) {
  const title = SECTION_TITLES[type] || SECTION_TITLES.other;
  let body;

  if (type === "skill") {
    body = renderSkillSection(modules);
  } else if (type === "summary") {
    body = renderSummarySection(modules);
  } else {
    const entry =
      type === "education" ? renderEducationEntry :
      type === "project" ? renderProjectEntry :
      renderExperienceEntry;
    const entries = modules.map(entry).filter(Boolean);
    body = entries.length
      ? [
          String.raw`  \resumeSubHeadingListStart`,
          ...entries,
          String.raw`  \resumeSubHeadingListEnd`
        ].join("\n")
      : "";
  }

  if (!body) return "";
  return `${String.raw`\section{${escapeLatex(title)}}`}\n${body}`;
}

/**
 * Groups modules by type while honouring the order they arrive in: a section
 * lands wherever its first module sits, so reordering modules in a tailored
 * resume reorders the sections too.
 */
export function groupByType(modules) {
  const groups = new Map();
  (modules || []).forEach(module => {
    const type = SECTION_TITLES[module.type] ? module.type : "other";
    if (!groups.has(type)) groups.set(type, []);
    groups.get(type).push(module);
  });
  return [...groups.entries()];
}

/**
 * Full LaTeX document for a list of modules, in the order given. Pass
 * `{ sortByTypeOrder: true }` to force the conventional section order
 * instead of honouring the incoming order.
 */
export function renderLatexResume(profile, modules, { sortByTypeOrder = false } = {}) {
  let groups = groupByType(modules);
  if (sortByTypeOrder) {
    groups = groups
      .slice()
      .sort((a, b) => TYPE_ORDER.indexOf(a[0]) - TYPE_ORDER.indexOf(b[0]));
  }

  const sections = groups
    .map(([type, mods]) => renderSection(type, mods))
    .filter(Boolean);

  return [
    PREAMBLE,
    "",
    String.raw`\begin{document}`,
    "",
    renderHeading(profile),
    "",
    ...sections.flatMap(s => [s, ""]),
    String.raw`\end{document}`,
    ""
  ].join("\n");
}

/** Safe filename for a downloaded .tex, e.g. "acme-frontend-dev.tex". */
export function latexFileName(...parts) {
  const slug = parts
    .filter(Boolean)
    .join("-")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
  return `${slug || "resume"}.tex`;
}
